geotrek/common/urls.py
from django.conf.urls import patterns, url
from mapentity.registry import MapEntityOptions

from .views import (JSSettings, admin_check_extents, DocumentPublic, import_view, import_update_json,
                    ThemeViewSet)


urlpatterns = patterns(
    '',
    url(r'^api/settings.json', JSSettings.as_view(), name='settings_json'),
    url(r'^tools/extents/', admin_check_extents, name='check_extents'),
    url(r'^commands/import-update.json$', import_update_json, name='import_update_json'),
    url(r'^commands/import$', import_view, name='import_dataset'),
    url(r'^api/(?P<lang>\w\w)/themes.json$', ThemeViewSet.as_view({'get': 'list'}), name="themes_json"),
)


class PublishableEntityOptions(MapEntityOptions):
    document_public_view = DocumentPublic

    def scan_views(self, *args, **kwargs):
        """ Adds the URLs of all views provided by ``PublishableMixin`` models.
        """
        views = super(PublishableEntityOptions, self).scan_views(*args, **kwargs)
        publishable_views = patterns(
            '',
            url(r'^api/(?P<lang>\w+)/{name}s/(?P<pk>\d+)/(?P<slug>[-_\w]+).pdf$'.format(name=self.modelname),
                self.document_public_view.as_view(model=self.model),
                name="%s_printable" % self.modelname),
        )
        return publishable_views + views

geotrek/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url, static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

from mapentity.forms import AttachmentForm

handler403 = 'mapentity.views.handler403'
handler404 = 'mapentity.views.handler404'
handler500 = 'mapentity.views.handler500'


urlpatterns = patterns(
    '',
    url(r'^api/v2/', include('geotrek.api.v2.urls', namespace='apiv2', app_name='apiv2')),
    url(r'^$', 'geotrek.core.views.home', name='home'),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': settings.ROOT_URL + '/'}, name='logout',),

    url(r'', include('geotrek.common.urls', namespace='common', app_name='common')),
    url(r'', include('geotrek.core.urls', namespace='core', app_name='core')),
    url(r'', include('geotrek.altimetry.urls', namespace='altimetry', app_name='altimetry')),
    url(r'', include('geotrek.land.urls', namespace='land', app_name='land')),
    url(r'', include('geotrek.zoning.urls', namespace='zoning', app_name='zoning')),
    url(r'', include('geotrek.infrastructure.urls', namespace='infrastructure', app_name='infrastructure')),
    url(r'', include('geotrek.maintenance.urls', namespace='maintenance', app_name='maintenance')),
    url(r'', include('geotrek.trekking.urls', namespace='trekking', app_name='trekking')),
    url(r'', include('geotrek.tourism.urls', namespace='tourism', app_name='tourism')),
    url(r'', include('geotrek.flatpages.urls', namespace='flatpages', app_name='flatpages')),
    url(r'', include('geotrek.feedback.urls', namespace='feedback', app_name='feedback')),



    url(r'', include('mapentity.urls', namespace='mapentity', app_name='mapentity')),
    url(r'^paperclip/add-for/(?P<app_label>[\w\-]+)/(?P<model_name>[\w\-]+)/(?P<pk>\d+)/$',
        'paperclip.views.add_attachment', kwargs={'attachment_form': AttachmentForm}, name="add_attachment"),
    url(r'^paperclip/update/(?P<attachment_pk>\d+)/$', 'paperclip.views.update_attachment',
        kwargs={'attachment_form': AttachmentForm}, name="update_attachment"),
    url(r'^paperclip/', include('paperclip.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG and settings.DEBUG_TOOLBAR:
    try:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns
    except ImportError:
        pass

geotrek/common/models.py
import os
from PIL import Image

from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _

from paperclip.models import FileType as BaseFileType, Attachment as BaseAttachment

from geotrek.authent.models import StructureRelated
from geotrek.common.mixins import PictogramMixin, OptionalPictogramMixin


class Organism(StructureRelated):

    organism = models.CharField(max_length=128, verbose_name=_(u"Organism"), db_column='organisme')

    class Meta:
        db_table = 'm_b_organisme'
        verbose_name = _(u"Organism")
        verbose_name_plural = _(u"Organisms")
        ordering = ['organism']

    def __unicode__(self):
        return self.organism


class FileType(StructureRelated, BaseFileType):
    """
    Attachment FileTypes, related to structure and with custom table name.
    """
    class Meta(BaseFileType.Meta):
        db_table = 'fl_b_fichier'

    @classmethod
    def objects_for(cls, request):
        """Override this method to filter form choices depending on structure.
        """
        return cls.for_user(request.user)


class Attachment(BaseAttachment):
    class Meta(BaseAttachment.Meta):
        db_table = 'fl_t_fichier'


class Theme(PictogramMixin):

    label = models.CharField(verbose_name=_(u"Label"), max_length=128, db_column='theme')
    cirkwi = models.ForeignKey('cirkwi.CirkwiTag', verbose_name=_(u"Cirkwi tag"), null=True, blank=True)

    class Meta:
        db_table = 'o_b_theme'
        verbose_name = _(u"Theme")
        verbose_name_plural = _(u"Themes")
        ordering = ['label']

    def __unicode__(self):
        return self.label

    @property
    def pictogram_off(self):
        """
        Since pictogram can be a sprite, we want to return the left part of
        the picture (crop right 50%).
        If the pictogram is a square, do not crop.
        """
        pictogram, ext = os.path.splitext(self.pictogram.name)
        pictopath = os.path.join(settings.MEDIA_ROOT, self.pictogram.name)
        output = os.path.join(settings.MEDIA_ROOT, pictogram + '_off' + ext)

        # Recreate only if necessary !
        is_empty = os.path.getsize(output) == 0
        is_newer = os.path.getmtime(pictopath) > os.path.getmtime(output)
        if not os.path.exists(output) or is_empty or is_newer:
            image = Image.open(pictopath)
            w, h = image.size
            if w > h:
                image = image.crop((0, 0, w / 2, h))
            image.save(output)
        return open(output)


class RecordSource(OptionalPictogramMixin):

    name = models.CharField(verbose_name=_(u"Name"), max_length=50)
    website = models.URLField(verbose_name=_(u"Website"), max_length=256,
                              db_column='website', blank=True, null=True)

    class Meta:
        db_table = 'o_b_source_fiche'
        verbose_name = _(u"Record source")
        verbose_name_plural = _(u"Record sources")
        ordering = ['name']

    def __unicode__(self):
        return self.name


class TargetPortal(models.Model):
    name = models.CharField(verbose_name=_(u"Name"), max_length=50, unique="True", help_text=_(u"Used for sync"))
    website = models.URLField(verbose_name=_(u"Website"), max_length=256,
                              db_column='website', unique="True")

    class Meta:
        db_table = 'o_b_target_portal'
        verbose_name = _(u"Target portal")
        verbose_name_plural = _(u"Target portals")
        ordering = ('name',)

    def __unicode__(self):
        return self.name

geotrek/common/views.py
# -*- coding: utf-8 -*-
from django.core.exceptions import ValidationError, PermissionDenied
from django.utils.decorators import method_decorator
from django.conf import settings
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db.utils import DatabaseError
from django.http import HttpResponse
from django.utils.translation import ugettext as _

from mapentity.helpers import api_bbox
from mapentity import views as mapentity_views

from geotrek.celery_conf import app as celery_app
from geotrek.common.utils import sql_extent
from geotrek import __version__

from rest_framework import permissions as rest_permissions, viewsets

# async data imports
import ast
import os
import json
import redis
from zipfile import ZipFile
from djcelery.models import TaskMeta
from datetime import datetime, timedelta

from .utils.import_celery import create_tmp_destination, discover_available_parsers

from .tasks import import_datas, import_datas_from_web
from .forms import ImportDatasetForm, ImportDatasetFormWithFile
from .models import Theme
from .serializers import ThemeSerializer


class FormsetMixin(object):
    context_name = None
    formset_class = None

    def form_valid(self, form):
        context = self.get_context_data()
        formset_form = context[self.context_name]

        if formset_form.is_valid():
            response = super(FormsetMixin, self).form_valid(form)
            formset_form.instance = self.object
            formset_form.save()
        else:
            response = self.form_invalid(form)
        return response

    def get_context_data(self, **kwargs):
        context = super(FormsetMixin, self).get_context_data(**kwargs)
        if self.request.POST:
            try:
                context[self.context_name] = self.formset_class(
                    self.request.POST, instance=self.object)
            except ValidationError:
                pass
        else:
            context[self.context_name] = self.formset_class(
                instance=self.object)
        return context


class PublicOrReadPermMixin(object):

    def get_object(self, queryset=None):
        obj = super(PublicOrReadPermMixin, self).get_object(queryset)
        if not obj.is_public():
            if not self.request.user.is_authenticated():
                raise PermissionDenied
            if not self.request.user.has_perm('%s.read_%s' % (obj._meta.app_label, obj._meta.model_name)):
                raise PermissionDenied
        return obj


class DocumentPublic(PublicOrReadPermMixin, mapentity_views.MapEntityDocumentWeasyprint):
    template_name_suffix = "_public"

    # Override view_permission_required
    def dispatch(self, *args, **kwargs):
        return super(mapentity_views.MapEntityDocumentBase, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(DocumentPublic, self).get_context_data(**kwargs)
        modelname = self.get_model()._meta.object_name.lower()
        context['mapimage_ratio'] = settings.EXPORT_MAP_IMAGE_SIZE[modelname]
        return context

#
# Concrete views
# ..............................


class JSSettings(mapentity_views.JSSettings):

    """ Override mapentity base settings in order to provide
    Geotrek necessary stuff.
    """
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(JSSettings, self).dispatch(*args, **kwargs)

    def get_context_data(self):
        dictsettings = super(JSSettings, self).get_context_data()
        # Add geotrek map styles
        base_styles = dictsettings['map']['styles']
        for name, override in settings.MAP_STYLES.items():
            merged = base_styles.get(name, {})
            merged.update(override)
            base_styles[name] = merged
        # Add extra stuff (edition, labelling)
        dictsettings['map'].update(
            snap_distance=settings.SNAP_DISTANCE,
            paths_line_marker=settings.PATHS_LINE_MARKER,
            colorspool=settings.COLORS_POOL,
        )
        dictsettings['version'] = __version__
        return dictsettings


@login_required
@user_passes_test(lambda u: u.is_superuser)
def admin_check_extents(request):
    """
    This view allows administrators to visualize data and configured extents.

    Since it's the first, we implemented this in a very rough way. If there is
    to be more admin tools like this one. Move this to a separate Django app and
    style HTML properly.
    """
    path_extent_native = sql_extent("SELECT ST_Extent(geom) FROM l_t_troncon;")
    path_extent = api_bbox(path_extent_native)
    try:
        dem_extent_native = sql_extent(
            "SELECT ST_Extent(rast::geometry) FROM mnt;")
        dem_extent = api_bbox(dem_extent_native)
    except DatabaseError:  # mnt table missing
        dem_extent_native = None
        dem_extent = None
    tiles_extent_native = settings.SPATIAL_EXTENT
    tiles_extent = api_bbox(tiles_extent_native)
    viewport_native = settings.LEAFLET_CONFIG['SPATIAL_EXTENT']
    viewport = api_bbox(viewport_native, srid=settings.API_SRID)

    def leafletbounds(bbox):
        return [[bbox[1], bbox[0]], [bbox[3], bbox[2]]]

    context = dict(
        path_extent=leafletbounds(path_extent),
        path_extent_native=path_extent_native,
        dem_extent=leafletbounds(dem_extent) if dem_extent else None,
        dem_extent_native=dem_extent_native,
        tiles_extent=leafletbounds(tiles_extent),
        tiles_extent_native=tiles_extent_native,
        viewport=leafletbounds(viewport),
        viewport_native=viewport_native,
        SRID=settings.SRID,
        API_SRID=settings.API_SRID,
    )
    return render(request, 'common/check_extents.html', context)


class UserArgMixin(object):

    def get_form_kwargs(self):
        kwargs = super(UserArgMixin, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


def import_file(uploaded, parser):
    destination_dir, destination_file = create_tmp_destination(uploaded.name)
    with open(destination_file, 'w+') as f:
        f.write(uploaded.file.read())
        zfile = ZipFile(f)
        for name in zfile.namelist():
            try:
                zfile.extract(
                    name, os.path.dirname(os.path.realpath(f.name)))
            except Exception:
                raise

            if name.endswith('shp'):
                import_datas.delay(parser.__name__, '/'.join((destination_dir, name)), parser.__module__)


@login_required
@user_passes_test(lambda u: u.is_superuser)
def import_view(request):
    """
    Gets the existing declared parsers for the current project.
    This view handles only the file based import parsers.
    """
    choices = []
    choices_url = []
    render_dict = {}

    choices, choices_url, classes = discover_available_parsers()

    form = ImportDatasetFormWithFile(choices, prefix="with-file")
    form_without_file = ImportDatasetForm(
        choices_url, prefix="without-file")

    if request.method == 'POST':
        if 'upload-file' in request.POST:
            form = ImportDatasetFormWithFile(
                choices, request.POST, request.FILES, prefix="with-file")

            if form.is_valid():
                uploaded = request.FILES['with-file-zipfile']
                parser = classes[int(form['parser'].value())]
                import_file(uploaded, parser)

        if 'import-web' in request.POST:
            form_without_file = ImportDatasetForm(
                choices_url, request.POST, prefix="without-file")

            if form_without_file.is_valid():
                parser = classes[int(form_without_file['parser'].value())]
                import_datas_from_web.delay(
                    parser.__name__, parser.__module__
                )

    # Hide second form if parser has no web based imports.
    render_dict['form'] = form
    if choices_url:
        render_dict['form_without_file'] = form_without_file

    return render(request, 'common/import_dataset.html', render_dict)


@login_required
@user_passes_test(lambda u: u.is_superuser)
def import_update_json(request):
    results = []
    threshold = datetime.now() - timedelta(seconds=60)
    for task in TaskMeta.objects.filter(date_done__gte=threshold).order_by('date_done'):
        if hasattr(task, 'result') and task.result.get('name', '').startswith('geotrek.common'):
            results.append(
                {
                    'id': task.task_id,
                    'result': task.result or {'current': 0, 'total': 0},
                    'status': task.status
                }
            )
    i = celery_app.control.inspect([u'celery@geotrek'])
    try:
        reserved = i.reserved()
    except redis.exceptions.ConnectionError:
        reserved = None
    tasks = [] if reserved is None else reversed(reserved[u'celery@geotrek'])
    for task in tasks:
        if task['name'].startswith('geotrek.common'):
            args = ast.literal_eval(task['args'])
            if task['name'].endswith('import-file'):
                filename = os.path.basename(args[1])
            else:
                filename = _("Import from web.")
            results.append(
                {
                    'id': task['id'],
                    'result': {
                        'parser': args[0],
                        'filename': filename,
                        'current': 0,
                        'total': 0
                    },
                    'status': 'PENDING',
                }
            )

    return HttpResponse(json.dumps(results), content_type="application/json")


class ThemeViewSet(viewsets.ModelViewSet):
    model = Theme
    queryset = Theme.objects.all()
    permission_classes = [rest_permissions.DjangoModelPermissionsOrAnonReadOnly]
    serializer_class = ThemeSerializer

    def get_queryset(self):
        qs = super(ThemeViewSet, self).get_queryset()

geotrek/common/templates/common/check_extents.html
{% load leaflet_tags i18n static %}
<html>
<head>
    {% leaflet_js %}
    <script src="{% static "leaflet/proj4js.js" %}" type="text/javascript"></script>
    <script src="{% static "proj4js/" %}{{ SRID }}.js" type="text/javascript"></script>

    {% leaflet_css %}
    <style>
        #map {
            height: 100%;
            width: 50%;
        }
        #infos {
            position: absolute;
            left: 50%;
            top: 0px;
        }
        tr.paths {
            color: #009F5F;
        }
        tr.tiles {
            color: #005EFF;
        }
        tr.dem {
            color: #CF00FF;
        }
        tr.viewport {
            color: #FF6E00;
        }
    </style>
</head>
<body>
    <div id="map"></div>
    <div id="infos">
        <table>
            <tr class="paths">
                <td>{% trans "Paths" %}</td>
                <td>BOX{{ path_extent_native }}</td>
            </tr>
            <tr class="tiles">
                <td>{% trans "Tiles" %}</td>
                <td>BOX{{ tiles_extent_native }}</td>
            </tr>
            <tr class="dem">
                <td>{% trans "DEM" %}</td>
                <td>{% if dem_extent %}BOX{{ dem_extent_native }}{% else %}{% trans "None" %}{% endif %}</td>
            </tr>
            <tr class="viewport">
                <td>{% trans "Viewport (WGS84)" %}</td>
                <td>BOX{{ viewport_native }}</td>
            </tr>
            <tr class="mouse">
                <td>{% trans "Mouse" %}</td>
                <td id="mouseposition"></td>
            </tr>
        </table>
    </div>
    <script type="text/javascript">
        (function () {
            var map = L.map('map');
            map.fitBounds({{ viewport }});

            var mouseMarker = L.marker();

            L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(map);

            L.rectangle({{ path_extent }}, {fillOpacity: 0, color: '#009F5F'}).addTo(map);
            L.rectangle({{ tiles_extent }}, {fillOpacity: 0, color: '#005EFF'}).addTo(map);
            L.rectangle({{ viewport }}, {fillOpacity: 0, color: '#FF6E00'}).addTo(map);
            {% if dem_extent %}
                L.rectangle({{ dem_extent }}, {fillOpacity: 0, color: '#CF00FF'}).addTo(map);
            {% endif %}

            map.on('click', function (e) {
                mouseMarker.setLatLng(L.latLng(e.latlng.lat, e.latlng.lng))
                           .addTo(map);
                var source = new Proj4js.Proj('EPSG:{{ API_SRID }}'),
                    dest = new Proj4js.Proj('EPSG:{{ SRID }}'),
                    pos = Proj4js.transform(source,
                                            dest,
                                            {x: e.latlng.lng, y: e.latlng.lat}),
                    td = document.getElementById('mouseposition');
                td.innerHTML = 'POINT(' + pos.x + ', ' + pos.y + ')';
            });

        })();
    </script>
</body>
</html>

geotrek/common/templates/common/common_extracss_fragment.html
{% load static %}
{# loaded by MapEntity, used to inject custom CSS at project level #}
<link rel="stylesheet" href="{% static "style.css" %}" />

geotrek/common/templates/common/common_menuentries_fragment.html
{% load i18n %}

{% if user.is_superuser %}
    <li><a href="{% url 'common:import_dataset' %}">{% trans "Imports" %}</a></li>
{% endif %}

geotrek/common/templates/common/import_dataset.html
{% extends "mapentity/base.html" %}
{% load static crispy_forms_tags %}

{% block extrahead %}
<script type="text/javascript" src="{% static "common/js/import.js" %}"></script>
<link rel="stylesheet" href="{% static "common/css/import.css" %}" />
{% endblock extrahead %}

{% block toolbar %}
{% endblock toolbar %}

{% block mainpanel %}
<div id="import-forms" class="span3 offset2">
	{% block mainform %}
	{% crispy form form.helper %}
	{% if form_without_file %}
		{% crispy form_without_file form_without_file.helper%}
	{% endif %}
	{% endblock mainform %}
</div>
<div id="progress-bars" class="span5">
</div>

<script id="import-template" type="text/template">
	<div id="progress-tpl">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<div class="description">
			<span class="parser"></span>
			<span class="filename">
			</span>
		</div>
		<div class="pull-left">
			<span></span>
		</div>
		<div class="progress progress-striped active">
			<div class="bar"></div>
		</div>
		<div class="alert">
			<span></span>
		</div>
		<hr></hr>
	</div>
</script>
{% endblock mainpanel %}

geotrek/common/templates/common/parser_report.html
{% load i18n %}

<button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#collapse-$celery_id">
  {%trans "Display report" %}
</button>

<div id="collapse-$celery_id" class="collapse">	
	<div class="nb-success">
	{% blocktrans count n=nb_success %}{{ n }}/{{ nb_lines }} line imported.{% plural %}{{ n }}/{{ nb_lines }} lines imported.{% endblocktrans %}
	</div>

	{% if nb_created %}
		<div class="nb-created">
		{% blocktrans count n=nb_created %}{{ n }} record created.{% plural %}{{ n }} records created.{% endblocktrans %}
		</div>
	{% endif %}

	{% if nb_updated %}
		<div class="nb-updated">
		{% blocktrans count n=nb_updated %}{{ n }} record updated.{% plural %}{{ n }} records updated.{% endblocktrans %}
		</div>
	{% endif %}

	{% if not nb_deleted == None %}
		<div class="nb-deleted">
		{% blocktrans count n=nb_deleted %}{{ n }} record deleted.{% plural %}{{ n }} records deleted.{% endblocktrans %}
		</div>
	{% endif %}

	{% if nb_unmodified %}
		<div class="nb-unmodified">
		{% blocktrans count n=nb_unmodified %}{{ n }} record unmodified.{% plural %}{{ n }} records unmodified.{% endblocktrans %}
		</div>
	{% endif %}

	{% if warnings %}
		<div class="warnings">
		{% blocktrans count n=warnings|length %}{{ n }} warning:{% plural %}{{ n }} warnings:{% endblocktrans %}
		
		<ul>
		{% for id, msgs in warnings.iteritems %}
			<li><div># {{ id }}:</div>
			{% for msg in msgs %}
				<div>- {{ msg|safe }},</div></li>
			{% endfor %}
		{% endfor %}
		</ul>
		</div>
	{% endif %}
</div>

geotrek/common/templates/common/publication_info_fragment.html
{% load static i18n mapentity_tags %}
<tr>
    <th>{{ object|verbose:"published" }}</th>
    <td>
    {% if object.any_published %}
        <ul>
        {% for status in object.published_status %}
            {% if status.status %}
            <li class="active">
                <img src="{% static "images/flags/"|add:status.lang|add:".png" %}" alt="{{ status.lang }}">
                <a href="?lang={{ status.lang }}">{{ status.language }}</a>
            </li>
            {% endif %}
        {% endfor %}
        </ul>
        ({{ object|verbose:"publication_date" }}: {{ object.publication_date }})
    {% else %}
        {% if object.review %}
            {% trans "Waiting for publication" %}
        {% else %}
            {% trans "Draft" %}
        {% endif %}
    {% endif %}
    </td>
</tr>

geotrek/common/templates/common/publishable_completeness_fragment.html
{% load i18n %}

{% if not object.any_published %}
    {% if object.review %}
        <div class="alert alert-warning"><strong>{% trans "Waiting for publication" %}</strong></div>
    {% else %}
        <div class="alert alert-info"><strong>{% trans "Draft" %}</strong></div>
    {% endif %}
{% else %}
    {% if not object.is_publishable %}
        <div class="alert alert-error"><strong>{% trans "Object is published but" %}</strong>
        {% if not object.is_complete %}{% trans "looks incomplete;" %}{% endif %}
        {% if not object.has_geom_valid %}{% trans "has invalid geometry;" %}{% endif %}
        </div>
    {% endif %}
{% endif %}