geotrek/trekking/urls.py
from django.conf.urls import patterns, url

from mapentity import registry

from geotrek.altimetry.urls import AltimetryEntityOptions
from geotrek.common.urls import PublishableEntityOptions
from mapentity.registry import MapEntityOptions

from . import models
from .views import (
    TrekDocumentPublic, POIDocumentPublic, TrekMapImage,
    TrekGPXDetail, TrekKMLDetail, WebLinkCreatePopup,
    CirkwiTrekView, CirkwiPOIView, TrekPOIViewSet,
    SyncRandoRedirect, TrekServiceViewSet, sync_view,
    sync_update_json
)
from . import serializers as trekking_serializers


urlpatterns = patterns(
    '',
    url(r'^api/(?P<lang>\w\w)/treks/(?P<pk>\d+)/pois\.geojson$', TrekPOIViewSet.as_view({'get': 'list'}), name="trek_poi_geojson"),
    url(r'^api/(?P<lang>\w\w)/treks/(?P<pk>\d+)/services\.geojson$', TrekServiceViewSet.as_view({'get': 'list'}), name="trek_service_geojson"),
    url(r'^api/(?P<lang>\w\w)/treks/(?P<pk>\d+)/(?P<slug>[-_\w]+).gpx$', TrekGPXDetail.as_view(), name="trek_gpx_detail"),
    url(r'^api/(?P<lang>\w\w)/treks/(?P<pk>\d+)/(?P<slug>[-_\w]+).kml$', TrekKMLDetail.as_view(), name="trek_kml_detail"),
    url(r'^popup/add/weblink/', WebLinkCreatePopup.as_view(), name='weblink_add'),
    url(r'^api/cirkwi/circuits.xml', CirkwiTrekView.as_view()),
    url(r'^api/cirkwi/pois.xml', CirkwiPOIView.as_view()),
    url(r'^commands/sync$', SyncRandoRedirect.as_view(), name='sync_randos'),
    url(r'^commands/syncview$', sync_view, name='sync_randos_view'),
    url(r'^commands/statesync/$', sync_update_json, name='sync_randos_state'),
    url(r'^image/trek-(?P<pk>\d+)-(?P<lang>\w\w).png$', TrekMapImage.as_view(), name='trek_map_image'),
)


class TrekEntityOptions(AltimetryEntityOptions, PublishableEntityOptions):
    """
    Add more urls using mixins:
    - altimetry views (profile, dem etc.)
    - public documents views
    We override trek public view to add more context variables and
    preprocess attributes.
    """
    document_public_view = TrekDocumentPublic

    def get_serializer(self):
        return trekking_serializers.TrekSerializer

    def get_queryset(self):
        return self.model.objects.existing()


class POIEntityOptions(PublishableEntityOptions):
    document_public_view = POIDocumentPublic

    def get_serializer(self):
        return trekking_serializers.POISerializer


class ServiceEntityOptions(MapEntityOptions):

    def get_serializer(self):
        return trekking_serializers.ServiceSerializer


urlpatterns += registry.register(models.Trek, TrekEntityOptions)
urlpatterns += registry.register(models.POI, POIEntityOptions)
urlpatterns += registry.register(models.Service, ServiceEntityOptions)

geotrek/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url, static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

from mapentity.forms import AttachmentForm

handler403 = 'mapentity.views.handler403'
handler404 = 'mapentity.views.handler404'
handler500 = 'mapentity.views.handler500'


urlpatterns = patterns(
    '',
    url(r'^api/v2/', include('geotrek.api.v2.urls', namespace='apiv2', app_name='apiv2')),
    url(r'^$', 'geotrek.core.views.home', name='home'),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': settings.ROOT_URL + '/'}, name='logout',),

    url(r'', include('geotrek.common.urls', namespace='common', app_name='common')),
    url(r'', include('geotrek.core.urls', namespace='core', app_name='core')),
    url(r'', include('geotrek.altimetry.urls', namespace='altimetry', app_name='altimetry')),
    url(r'', include('geotrek.land.urls', namespace='land', app_name='land')),
    url(r'', include('geotrek.zoning.urls', namespace='zoning', app_name='zoning')),
    url(r'', include('geotrek.infrastructure.urls', namespace='infrastructure', app_name='infrastructure')),
    url(r'', include('geotrek.maintenance.urls', namespace='maintenance', app_name='maintenance')),
    url(r'', include('geotrek.trekking.urls', namespace='trekking', app_name='trekking')),
    url(r'', include('geotrek.tourism.urls', namespace='tourism', app_name='tourism')),
    url(r'', include('geotrek.flatpages.urls', namespace='flatpages', app_name='flatpages')),
    url(r'', include('geotrek.feedback.urls', namespace='feedback', app_name='feedback')),



    url(r'', include('mapentity.urls', namespace='mapentity', app_name='mapentity')),
    url(r'^paperclip/add-for/(?P<app_label>[\w\-]+)/(?P<model_name>[\w\-]+)/(?P<pk>\d+)/$',
        'paperclip.views.add_attachment', kwargs={'attachment_form': AttachmentForm}, name="add_attachment"),
    url(r'^paperclip/update/(?P<attachment_pk>\d+)/$', 'paperclip.views.update_attachment',
        kwargs={'attachment_form': AttachmentForm}, name="update_attachment"),
    url(r'^paperclip/', include('paperclip.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG and settings.DEBUG_TOOLBAR:
    try:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns
    except ImportError:
        pass

geotrek/trekking/forms.py
from copy import deepcopy

from django.utils.translation import ugettext as _
from django.conf import settings
from django.core.exceptions import ValidationError
from django.forms.models import inlineformset_factory

import floppyforms as forms
from crispy_forms.helper import FormHelper
from crispy_forms.bootstrap import FormActions
from crispy_forms.layout import Layout, Submit, HTML, Div, Fieldset
from leaflet.forms.widgets import LeafletWidget
from mapentity.widgets import SelectMultipleWithPop

from geotrek.common.forms import CommonForm
from geotrek.core.forms import TopologyForm
from geotrek.core.widgets import LineTopologyWidget, PointTopologyWidget
from .models import Trek, POI, WebLink, Service, ServiceType, OrderedTrekChild
from django.db import transaction
from django.core.urlresolvers import reverse


class TrekRelationshipForm(forms.ModelForm):

    class Meta:
        fields = ('id',
                  'trek_a',
                  'trek_b',
                  'has_common_departure',
                  'has_common_edge',
                  'is_circuit_step')

    def __init__(self, *args, **kwargs):
        super(TrekRelationshipForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout('id',
                                    'trek_a',
                                    'trek_b',
                                    'has_common_departure',
                                    'has_common_edge',
                                    'is_circuit_step',
                                    'DELETE')


TrekRelationshipFormSet = inlineformset_factory(Trek, Trek.related_treks.through,
                                                form=TrekRelationshipForm, fk_name='trek_a',
                                                extra=1)

if settings.TREKKING_TOPOLOGY_ENABLED:

    class BaseTrekForm(TopologyForm):
        def __init__(self, *args, **kwargs):
            super(BaseTrekForm, self).__init__(*args, **kwargs)
            self.fields['topology'].widget = LineTopologyWidget()
            self.fields['points_reference'].label = ''
            self.fields['points_reference'].widget.target_map = 'topology'
            self.fields['parking_location'].label = ''
            self.fields['parking_location'].widget.target_map = 'topology'

        class Meta(TopologyForm.Meta):
            model = Trek
else:

    class BaseTrekForm(CommonForm):
        geomfields = ['geom']

        def __init__(self, *args, **kwargs):
            super(BaseTrekForm, self).__init__(*args, **kwargs)
            self.fields['geom'].widget = LeafletWidget(attrs={'geom_type': 'LINESTRING'})
            self.fields['points_reference'].label = ''
            self.fields['points_reference'].widget.target_map = 'geom'
            self.fields['parking_location'].label = ''
            self.fields['parking_location'].widget.target_map = 'geom'

        class Meta(CommonForm.Meta):
            model = Trek
            fields = CommonForm.Meta.fields + ['geom']


class TrekForm(BaseTrekForm):
    children_trek = forms.ModelMultipleChoiceField(label=_(u"Children"),
                                                   queryset=Trek.objects.all(), required=False,
                                                   help_text=_(u"Select children in order"))
    hidden_ordered_children = forms.CharField(label=_(u"Hidden ordered children"),
                                              widget=forms.widgets.HiddenInput(),
                                              required=False)

    leftpanel_scrollable = False

    base_fieldslayout = [
        Div(
            HTML("""
            <ul class="nav nav-tabs">
                <li id="tab-main" class="active"><a href="#main" data-toggle="tab"><i class="icon-certificate"></i> %s</a></li>
                <li id="tab-advanced"><a href="#advanced" data-toggle="tab"><i class="icon-tasks"></i> %s</a></li>
            </ul>""" % (unicode(_("Main")), unicode(_("Advanced")))),
            Div(
                Div(
                    'name',
                    'review',
                    'published',
                    'is_park_centered',
                    'departure',
                    'arrival',
                    'duration',
                    'difficulty',
                    'route',
                    'ambiance',
                    'access',
                    'description_teaser',
                    'description',
                    css_id="main",
                    css_class="scrollable tab-pane active"
                ),
                Div(
                    'points_reference',
                    'disabled_infrastructure',
                    'advised_parking',
                    'parking_location',
                    'public_transport',
                    'advice',
                    'themes',
                    'networks',
                    'practice',
                    'accessibilities',
                    'web_links',
                    'information_desks',
                    'source',
                    'portal',
                    'children_trek',
                    'eid',
                    'eid2',
                    'hidden_ordered_children',
                    Fieldset(_("Related treks"),),
                    css_id="advanced",  # used in Javascript for activating tab if error
                    css_class="scrollable tab-pane"
                ),
                css_class="tab-content"
            ),
            css_class="tabbable"
        ),
    ]

    def __init__(self, *args, **kwargs):
        self.fieldslayout = deepcopy(self.base_fieldslayout)
        self.fieldslayout[0][1][0].append(HTML('<div class="controls">' + _('Insert service:') + ''.join(['<a class="servicetype" data-url="{url}" data-name={name}"><img src="{url}"></a>'.format(url=t.pictogram.url, name=t.name) for t in ServiceType.objects.all()]) + '</div>'))

        super(TrekForm, self).__init__(*args, **kwargs)

        self.fields['web_links'].widget = SelectMultipleWithPop(choices=self.fields['web_links'].choices,
                                                                add_url=WebLink.get_add_url())
        # Make sure (force) that name is required, in default language only
        self.fields['name_%s' % settings.LANGUAGE_CODE].required = True

        if not settings.TREK_POINTS_OF_REFERENCE_ENABLED:
            self.fields.pop('points_reference')
        else:
            # Edit points of reference with custom edition JavaScript class
            self.fields['points_reference'].widget.geometry_field_class = 'PointsReferenceField'

        self.fields['parking_location'].widget.geometry_field_class = 'ParkingLocationField'
        self.fields['duration'].widget.attrs['min'] = '0'

        # Since we use chosen() in trek_form.html, we don't need the default help text
        for f in ['themes', 'networks', 'accessibilities',
                  'web_links', 'information_desks', 'source', 'portal']:
            self.fields[f].help_text = ''

        if self.instance:
            queryset_children = OrderedTrekChild.objects.filter(parent__id=self.instance.pk)\
                                                        .order_by('order')
            # init multiple children field with data
            self.fields['children_trek'].queryset = Trek.objects.existing().exclude(pk=self.instance.pk)
            self.fields['children_trek'].initial = [c.child.pk for c in self.instance.trek_children.all()]

            # init hidden field with children order
            self.fields['hidden_ordered_children'].initial = ",".join(str(x) for x in queryset_children.values_list('child__id', flat=True))

    def clean_children_trek(self):
        """
        Check the trek is not parent and child at the same time
        """
        children = self.cleaned_data['children_trek']
        if children and self.instance and self.instance.trek_parents.exists():
            raise ValidationError(_(u"Cannot add children because this trek is itself a child."))
        for child in children:
            if child.trek_children.exists():
                raise ValidationError(_(u"Cannot use parent trek {name} as a child trek.".format(name=child.name)))
        return children

    def clean_duration(self):
        """For duration, an HTML5 "number" field is used. If the user fills an invalid
        number (like "2H40"), the browser will submit an empty value (!).
        Here we default to 0.0
        """
        duration = self.cleaned_data.get('duration')
        return 0.0 if duration is None else duration

    def save(self, *args, **kwargs):
        """
        Custom form save override - ordered children management
        """
        sid = transaction.savepoint()

        try:
            return_value = super(TrekForm, self).save(self, *args, **kwargs)
            ordering = []

            if self.cleaned_data['hidden_ordered_children']:
                ordering = self.cleaned_data['hidden_ordered_children'].split(',')

            order = 0

            # add and update
            for value in ordering:
                child, created = OrderedTrekChild.objects.get_or_create(parent=self.instance,
                                                                        child=Trek.objects.get(pk=value))
                child.order = order
                child.save()
                order += 1

            # delete
            new_list_children = self.cleaned_data['children_trek'].values_list('pk', flat=True)

            for child_relation in self.instance.trek_children.all():
                # if existant child not in selection, deletion
                if child_relation.child_id not in new_list_children:
                    child_relation.delete()

            transaction.savepoint_commit(sid)
            return return_value

        except Exception as exc:
            transaction.savepoint_rollback(sid)

geotrek/trekking/templates/trekking/poi_detail.html
{% extends "mapentity/mapentity_detail.html" %}
{% load static i18n mapentity_tags %}


{% block attachmentspanel %}
    {% include "trekking/ratio_info_fragment.html" %}
    {{ block.super }}
{% endblock attachmentspanel %}


{% block download %}
    {{ block.super }}
  </div>

  <div class="btn-group pull-right">
    <a class="btn btn-mini" href="{% url 'trekking:poi_printable' LANGUAGE_CODE object.pk object.slug %}" title="{% trans "Public print" %}" target="_blank"><img src="{% static "paperclip/fileicons/pdf.png" %}"/> {% trans "Print" %}</a>
{% endblock download %}


{% block detailspanel %}
    {% include "common/publishable_completeness_fragment.html" %}
    {{ block.super }}
{% endblock detailspanel %}

geotrek/trekking/templates/trekking/poi_detail_attributes.html
{% extends "mapentity/mapentity_detail_attributes.html" %}
{% load i18n mapentity_tags %}

{% block attributes %}
    <h3>{% trans "Attributes" %}</h3>

    <table class="table-striped table-bordered table">
         <tr>
            <th>{{ poi|verbose:"type" }}</th>
            <td>{{ poi.type }}</td>
        </tr>
        <tr>
            <th>{{ poi|verbose:"name" }}</th>
            <td>{{ poi.name }}</td>
        </tr>
        <tr>
            <th>{{ poi|verbose:"description" }}</th>
            <td>{% if poi.description %}{{ poi.description|safe }}
                {% else %}<span class="none">{% trans "None" %}</span>{% endif %}</td>
        </tr>
        <tr>
            <th>{% trans "Thumbnail" %}</th>
            <td><img src="{{ poi.thumbnail.url }}"></td>
        </tr>
        <tr>
            <th>{% trans "External id" %}</th>
            <td>{{ poi.eid }}</td>
        </tr>

        {% include "altimetry/elevationinfo_fragment.html" %}
        {% include "common/publication_info_fragment.html" %}
        {% include "mapentity/trackinfo_fragment.html" %}
    </table>

    {{ block.super }}
{% endblock attributes %}

geotrek/trekking/templates/trekking/poi_form.html
{% extends "mapentity/mapentity_form.html" %}

{% load staticfiles %}


{% block extrabody %}
    {{ block.super }}
    <script type="text/javascript" src="{% static "common/js/main.js" %}"></script>
{% endblock extrabody %}

geotrek/trekking/templates/trekking/poi_public_pdf.html
{% load i18n mapentity_tags %}

<img src="{% media_static_fallback "upload/logo-header.png" "images/logo-header.png" %}">

<h2>{{ object.name }}</h2>

<h3>{{ object.districts.0 }}</h3>
<h3>{{ object.cities.0 }}</h3>

{% if object.picture_print %}
  <img src="{{ MEDIA_URL}}/{{ object.picture_print.name }}">
{% endif %}

<table>
	<tr>
		<th>
			{% trans "Type" %}
		</th>
		<td>
			{{ object.type }}
		</td>
	</tr>
	<tr>
		<th>
			{% trans "Elevation" %}
		</th>
		<td>
			{{ object.min_elevation }} m
		</td>
	</tr>
</table>

<p>{{ object.description|safe }}</p>

{% if object.treks.count > 0 %}
	<h4>{% trans "Treks" %}</h4>
	<table>
		{% for other in object.treks.all %}
			<tr>
				<td>{{ other.name }}</td>
			</tr>
		{% endfor %}
	</table>
{% endif %}

<img src="{{ map_url }}" style="margin-left: auto; margin-right: auto; width: 100%; height: auto; ">

{% if object.pictures.0.legend or object.pictures.0.author %}
	<p>{% trans "Attribution" %} : {{ object.pictures.0.legend }} ({{ object.pictures.0.author }})</p>
{% endif %}

<a href="http://geotrek.fr">{% trans "Powered by http://geotrek.fr" %}</a>

geotrek/trekking/templates/trekking/ratio_info_fragment.html
{% load i18n %}
<div class="alert alert-info">
    <strong>{% trans "Your <strong>pictures should have the same ratio<strong> (height/width) for a better apparence in public portal." %}</strong>
</div>

geotrek/trekking/templates/trekking/service_detail_attributes.html
{% extends "mapentity/mapentity_detail_attributes.html" %}
{% load i18n mapentity_tags %}

{% block attributes %}
    <h3>{% trans "Attributes" %}</h3>

    <table class="table-striped table-bordered table">
         <tr>
            <th>{{ service|verbose:"type" }}</th>
            <td>{{ service.type }}</td>
        </tr>
        <tr>
            <th>{% trans "External id" %}</th>
            <td>{{ poi.eid }}</td>
        </tr>

        {% include "altimetry/elevationinfo_fragment.html" %}
        {% include "mapentity/trackinfo_fragment.html" %}
    </table>

    {{ block.super }}
{% endblock attributes %}

geotrek/trekking/templates/trekking/service_form.html
{% extends "mapentity/mapentity_form.html" %}

{% load staticfiles %}


{% block extrabody %}
    {{ block.super }}
    <script type="text/javascript" src="{% static "common/js/main.js" %}"></script>
{% endblock extrabody %}

geotrek/trekking/templates/trekking/trek_detail_pdf.html
{% load i18n mapentity_tags staticfiles %}

{% block body %}
	<body>
	{% block style %}

		<style type="text/css">
			{% include template_css %}
		</style>
	{% endblock style %}

	{% block EntityDetail %}

 		{% include template_attributes %}

		{% block Map %}
			<h3>{% trans "Map" %}</h3>
			<img src="{{ map_url }}" id="EntityScreenshot">
		{% endblock Map %}

		{% block Altimetry %}
			{% if object.get_elevation_chart_url %}
			    <h3>Elevation</h3>
			    <img src="{{ object.get_elevation_chart_url }}" style="margin-left: auto; margin-right: auto; width: 100%; height: auto; ">
		    {% endif %}
		{% endblock Altimetry %}

	{% endblock EntityDetail %}
	</body>
{% endblock body %}

geotrek/trekking/templates/trekking/trek_form.html
{% extends "mapentity/mapentity_form.html" %}

{% load i18n crispy_forms_tags staticfiles %}

{% block mainform %}

    <script type="text/javascript" src="{% static 'trekking/chosen.order.jquery.min.js' %}"></script>
    <script type="text/javascript" src="https://code.jquery.com/ui/1.11.3/jquery-ui.min.js"></script>

    <script type="text/javascript">
        $(function(){
            $("#id_children_trek").change(function(){
               $("#id_hidden_ordered_children").val($("#id_children_trek").getSelectionOrder().toString());
            });

            $('#id_children_trek_chosen').find('ul').sortable();
        });
    </script>

    <form id="mainform" action="{% if object.pk %}{{ object.get_update_url }}{% else %}{{ object.get_add_url }}{% endif %}" class="form-horizontal" method="POST">
        {% crispy form %}
        <fieldset class="formset">
            {{ relationship_formset.management_form }}
            {% for relationship_form in relationship_formset %}
                <div class="form-row inline controls controls-row {{ relationship_formset.prefix }}">
                {% crispy relationship_form %}
                </div>
            {% endfor %}
        </fieldset>
    </form>
{% endblock mainform %}


{% block extrabody %}
    {{ block.super }}
    <script type="text/javascript" src="{% static "common/js/main.js" %}"></script>
    <script type="text/javascript">
        MapEntity.i18n['Add a point of reference'] = "{% trans "Add a point of reference" %}";
        MapEntity.i18n['Move points of reference'] = "{% trans "Move points of reference" %}";
        MapEntity.i18n['Delete a point of reference'] = "{% trans "Delete a point of reference" %}";
        MapEntity.i18n['Set the parking location'] = "{% trans "Set the parking location" %}";
        MapEntity.i18n['Move the parking location'] = "{% trans "Move the parking location" %}";
        MapEntity.i18n['Delete the parking location'] = "{% trans "Delete the parking location" %}";

        $(document).ready(function() {
            // TODO: do this with crispyforms !
            $("fieldset.formset").detach().appendTo('#mainform fieldset');

            $('.form-row.inline.{{ relationship_formset.prefix }}').formset({
                prefix: '{{ relationship_formset.prefix }}',
                keepFieldValues: "[name='csrfmiddlewaretoken']",
                addCssClass: 'btn btn-success add-row',
                deleteCssClass: 'delete-row',
                addText: '{% trans "Add relation" %}',
                deleteText: '{% trans "Remove" %}'
            });

            $('select[multiple]').chosen({
                no_results_text: "{% trans "No result" %}",
                placeholder_text_multiple: "{% trans "Choose value(s)" %}"
            });

            /* Show advanced tab if error in there */
            if ($('.tab-content #advanced .error').length > 0) {
                $('#tab-advanced').find('a').addClass('error').click();
            }

            // Tab changed
            $('.nav-tabs a').on('shown', function (e) {
                // Recompute scrollable panels
                $(window).trigger('resize');
            });

            // Insert service buttons
            $('.servicetype').click(function(e) {
                var url = $(this).data('url');
                var name = $(this).data('name');
                var id = $('div[id^="description_"]:not([id*="teaser"]):visible textarea').attr('id');
                tinymce.get(id).execCommand('mceInsertContent', false, '<img src="' + url + '" alt="' + name + '" />');
                return false;
            });

            $("#id_children_trek").setSelectionOrder($("#id_hidden_ordered_children").val().split(","));
        });

    </script>
{% endblock extrabody %}

geotrek/trekking/templates/trekking/trekking_menuentries_fragment.html
{% load i18n %}

{% if user.is_superuser %}
    <li><a href="{% url 'trekking:sync_randos_view' %}">{% trans "Sync" %}</a></li>
{% endif %}

geotrek/trekking/templates/trekking/weblink_form.html
{% extends "mapentity/base.html" %}
{% load static i18n crispy_forms_tags %}

{% block title %}{% trans "Add Web link" %}{% endblock title %}

{% block navbar %}{% endblock navbar %}

{% block content %}
    <h3>{% trans "Add Web link"%}</h3>
    {% crispy form %}
{% endblock content %}