geotrek/maintenance/urls.py
from mapentity import registry

from . import models


urlpatterns = registry.register(models.Intervention)
urlpatterns += registry.register(models.Project)

geotrek/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url, static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

from mapentity.forms import AttachmentForm

handler403 = 'mapentity.views.handler403'
handler404 = 'mapentity.views.handler404'
handler500 = 'mapentity.views.handler500'


urlpatterns = patterns(
    '',
    url(r'^api/v2/', include('geotrek.api.v2.urls', namespace='apiv2', app_name='apiv2')),
    url(r'^$', 'geotrek.core.views.home', name='home'),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': settings.ROOT_URL + '/'}, name='logout',),

    url(r'', include('geotrek.common.urls', namespace='common', app_name='common')),
    url(r'', include('geotrek.core.urls', namespace='core', app_name='core')),
    url(r'', include('geotrek.altimetry.urls', namespace='altimetry', app_name='altimetry')),
    url(r'', include('geotrek.land.urls', namespace='land', app_name='land')),
    url(r'', include('geotrek.zoning.urls', namespace='zoning', app_name='zoning')),
    url(r'', include('geotrek.infrastructure.urls', namespace='infrastructure', app_name='infrastructure')),
    url(r'', include('geotrek.maintenance.urls', namespace='maintenance', app_name='maintenance')),
    url(r'', include('geotrek.trekking.urls', namespace='trekking', app_name='trekking')),
    url(r'', include('geotrek.tourism.urls', namespace='tourism', app_name='tourism')),
    url(r'', include('geotrek.flatpages.urls', namespace='flatpages', app_name='flatpages')),
    url(r'', include('geotrek.feedback.urls', namespace='feedback', app_name='feedback')),



    url(r'', include('mapentity.urls', namespace='mapentity', app_name='mapentity')),
    url(r'^paperclip/add-for/(?P<app_label>[\w\-]+)/(?P<model_name>[\w\-]+)/(?P<pk>\d+)/$',
        'paperclip.views.add_attachment', kwargs={'attachment_form': AttachmentForm}, name="add_attachment"),
    url(r'^paperclip/update/(?P<attachment_pk>\d+)/$', 'paperclip.views.update_attachment',
        kwargs={'attachment_form': AttachmentForm}, name="update_attachment"),
    url(r'^paperclip/', include('paperclip.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG and settings.DEBUG_TOOLBAR:
    try:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns
    except ImportError:
        pass

geotrek/maintenance/models.py
# -*- coding: utf-8 -*-
import os
from datetime import datetime

from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.contrib.gis.db import models
from django.contrib.gis.geos import GeometryCollection

from mapentity.models import MapEntityMixin

from geotrek.authent.models import StructureRelated
from geotrek.altimetry.models import AltimetryMixin
from geotrek.core.models import Topology, Path, Trail
from geotrek.common.models import Organism
from geotrek.common.mixins import TimeStampedModelMixin, NoDeleteMixin, AddPropertyMixin
from geotrek.common.utils import classproperty
from geotrek.infrastructure.models import Infrastructure, Signage


class InterventionManager(models.GeoManager):
    def all_years(self):
        all_dates = self.existing().values_list('date', flat=True)
        all_years = list(reversed(sorted(set([d.year for d in all_dates]))))
        return all_years


class Intervention(AddPropertyMixin, MapEntityMixin, AltimetryMixin,
                   TimeStampedModelMixin, StructureRelated, NoDeleteMixin):

    name = models.CharField(verbose_name=_(u"Name"), max_length=128, db_column='nom',
                            help_text=_(u"Brief summary"))
    date = models.DateField(default=datetime.now, verbose_name=_(u"Date"), db_column='date',
                            help_text=_(u"When ?"))
    subcontracting = models.BooleanField(verbose_name=_(u"Subcontracting"), default=False,
                                         db_column='sous_traitance')

    # Technical information
    width = models.FloatField(default=0.0, verbose_name=_(u"Width"), db_column='largeur')
    height = models.FloatField(default=0.0, verbose_name=_(u"Height"), db_column='hauteur')
    area = models.FloatField(editable=False, default=0, verbose_name=_(u"Area"), db_column='surface')

    # Costs
    material_cost = models.FloatField(default=0.0, verbose_name=_(u"Material cost"), db_column='cout_materiel')
    heliport_cost = models.FloatField(default=0.0, verbose_name=_(u"Heliport cost"), db_column='cout_heliport')
    subcontract_cost = models.FloatField(default=0.0, verbose_name=_(u"Subcontract cost"), db_column='cout_soustraitant')

    """ Topology can be of type Infrastructure or of own type Intervention """
    topology = models.ForeignKey(Topology, null=True,  # TODO: why null ?
                                 related_name="interventions_set",
                                 verbose_name=_(u"Interventions"))
    # AltimetyMixin for denormalized fields from related topology, updated via trigger.

    stake = models.ForeignKey('core.Stake', null=True,
                              related_name='interventions', verbose_name=_("Stake"), db_column='enjeu')

    status = models.ForeignKey('InterventionStatus', verbose_name=_("Status"), db_column='status')

    type = models.ForeignKey('InterventionType', null=True, blank=True,
                             verbose_name=_(u"Type"), db_column='type')

    disorders = models.ManyToManyField('InterventionDisorder', related_name="interventions",
                                       db_table="m_r_intervention_desordre", verbose_name=_(u"Disorders"),
                                       blank=True)

    jobs = models.ManyToManyField('InterventionJob', through='ManDay', verbose_name=_(u"Jobs"))

    project = models.ForeignKey('Project', null=True, blank=True, related_name="interventions",
                                verbose_name=_(u"Project"), db_column='chantier')
    description = models.TextField(blank=True, verbose_name=_(u"Description"), db_column='descriptif',
                                   help_text=_(u"Remarks and notes"))

    objects = NoDeleteMixin.get_manager_cls(InterventionManager)()

    class Meta:
        db_table = 'm_t_intervention'
        verbose_name = _(u"Intervention")
        verbose_name_plural = _(u"Interventions")

    def __init__(self, *args, **kwargs):
        super(Intervention, self).__init__(*args, **kwargs)
        self._geom = None

    def set_infrastructure(self, baseinfra):
        self.topology = baseinfra
        if not self.on_infrastructure:
            raise ValueError("Expecting an infrastructure or signage")

    def default_stake(self):
        stake = None
        if self.topology:
            for path in self.topology.paths.all():
                if path.stake > stake:
                    stake = path.stake
        return stake

    def reload(self, fromdb=None):
        if self.pk:
            fromdb = self.__class__.objects.get(pk=self.pk)
            self.area = fromdb.area
            AltimetryMixin.reload(self, fromdb)
            TimeStampedModelMixin.reload(self, fromdb)
            NoDeleteMixin.reload(self, fromdb)
            if self.topology:
                self.topology.reload()
        return self

    def save(self, *args, **kwargs):
        if self.stake is None:
            self.stake = self.default_stake()

        super(Intervention, self).save(*args, **kwargs)

        # Set kind of Intervention topology
        if self.topology and not self.on_infrastructure:
            topology_kind = self._meta.object_name.upper()
            self.topology.kind = topology_kind
            self.topology.save(update_fields=['kind'])

        # Invalidate project map
        if self.project:
            try:
                os.remove(self.project.get_map_image_path())
            except OSError:
                pass

        self.reload()

    @property
    def on_infrastructure(self):
        return self.is_infrastructure or self.is_signage

    @property
    def infrastructure(self):
        """
        Equivalent of topology attribute, but casted to related type (Infrastructure or Signage)
        """
        if self.on_infrastructure:
            if self.is_signage:
                return self.signages[0]
            if self.is_infrastructure:
                return self.infrastructures[0]
        return None

    @classproperty
    def infrastructure_verbose_name(cls):
        return _("On")

    @property
    def infrastructure_display(self):
        icon = 'path'
        title = _('Path')
        if self.on_infrastructure:
            icon = self.topology.kind.lower()
            title = u'%s: %s' % (_(self.topology.kind.capitalize()),
                                 self.infrastructure)

        return u'<img src="%simages/%s-16.png" title="%s">' % (settings.STATIC_URL,
                                                               icon,
                                                               title)

    @property
    def infrastructure_csv_display(self):
        if self.on_infrastructure:
            return u"%s: %s (%s)" % (
                _(self.topology.kind.capitalize()),
                self.infrastructure,
                self.infrastructure.pk)
        return ''

    @property
    def is_infrastructure(self):
        if self.topology:
            return self.topology.kind == Infrastructure.KIND
        return False

    @property
    def is_signage(self):
        if self.topology:
            return self.topology.kind == Signage.KIND
        return False

    @property
    def in_project(self):
        return self.project is not None

    @property
    def paths(self):
        if self.topology:
            return self.topology.paths.all()
        return Path.objects.none()

    @property
    def signages(self):
        if self.is_signage:
            return [Signage.objects.existing().get(pk=self.topology.pk)]
        return []

    @property
    def infrastructures(self):
        if self.is_infrastructure:
            return [Infrastructure.objects.existing().get(pk=self.topology.pk)]
        return []

    @property
    def total_manday(self):
        total = 0.0
        for md in self.manday_set.all():
            total += float(md.nb_days)
        return total

    @classproperty
    def total_manday_verbose_name(cls):
        return _("Mandays")

    @property
    def total_cost_mandays(self):
        total = 0.0
        for md in self.manday_set.all():
            total += md.cost
        return total

    @classproperty
    def total_cost_mandays_verbose_name(cls):
        return _("Mandays cost")

    @property
    def total_cost(self):
        return self.total_cost_mandays + \
            self.material_cost + \
            self.heliport_cost + \
            self.subcontract_cost

    @classproperty
    def total_cost_verbose_name(cls):
        return _("Total cost")

    @classproperty
    def geomfield(cls):
        return Topology._meta.get_field('geom')

    @property
    def geom(self):
        if self._geom is None:
            if self.topology:
                self._geom = self.topology.geom
        return self._geom

    @geom.setter
    def geom(self, value):
        self._geom = value

    @property
    def name_display(self):
        return u'<a data-pk="%s" href="%s" title="%s" >%s</a>' % (self.pk,
                                                                  self.get_detail_url(),
                                                                  self.name,
                                                                  self.name)

    @property
    def name_csv_display(self):
        return unicode(self.name)

    def __unicode__(self):
        return u"%s (%s)" % (self.name, self.date)

    @classmethod
    def path_interventions(cls, path):
        return cls.objects.existing().filter(topology__aggregations__path=path)

    @classmethod
    def topology_interventions(cls, topology):
        topos = Topology.overlapping(topology).values_list('pk', flat=True)
        return cls.objects.existing().filter(topology__in=topos).distinct('pk')


Path.add_property('interventions', lambda self: Intervention.path_interventions(self), _(u"Interventions"))
Topology.add_property('interventions', lambda self: Intervention.topology_interventions(self), _(u"Interventions"))


class InterventionStatus(StructureRelated):

geotrek/maintenance/templates/maintenance/intervention_detail.html
{% extends "mapentity/mapentity_detail.html" %}
{% load i18n static mapentity_tags %}

{% block detailspanel %}
    <table class="table-striped table-bordered table">
        <tr>
            <th>{{ intervention|verbose:"name" }}</th>
            <td>{{ intervention.name }}</td>
        </tr>
        <tr>
            <th>{{ intervention|verbose:"date" }}</th>
            <td>{{ intervention.date }}</td>
        </tr>
        <tr>
            <th>{{ intervention|verbose:"stake" }}</th>
            <td>{% if intervention.stake %}<span class="label">{{ intervention.stake }}</span>
                {% else %}<span class="none">{% trans "None" %}</span>{% endif %}
            </td>
        </tr>
         <tr>
            <th>{{ intervention|verbose:"status" }}</th>
            <td>{% if intervention.status %}{{ intervention.status }}
                {% else %}<span class="none">{% trans "None" %}</span>{% endif %}
            </td>
        </tr>
        <tr>
            <th>{{ intervention|verbose:"type" }}</th>
            <td>{% if intervention.type %}{{ intervention.type }}
                {% else %}<span class="none">{% trans "None" %}</span>{% endif %}
            </td>
        </tr>
        <tr>
            <th>{{ intervention|verbose:"subcontracting" }}</th>
            <td>{% if intervention.subcontracting %}{% trans "Yes" %}{% else %}{% trans "No" %}{% endif %}</td>
        </tr>
        <tr>
            <th>{{ intervention|verbose:"disorders" }}</th>
            <td>
                {% for disorder in  intervention.disorders.all %}
                    {% if forloop.first %}<ul>{% endif %}
                    <li> {{ disorder }} </li>
                    {% if forloop.last %}</ul>{% endif %}
                {% empty %}
                    <span class="none">{% trans "None" %}</span>
                {% endfor %}
            </td>
        </tr>
        <tr>
            <th>{{ intervention|verbose:"material_cost" }}</th>
            <td>{{ intervention.material_cost|floatformat:2 }} &euro;</td>
        </tr>
        <tr>
            <th>{{ intervention|verbose:"heliport_cost" }}</th>
            <td>{{ intervention.heliport_cost|floatformat:2 }} &euro;</td>
        </tr>
        <tr>
            <th>{{ intervention|verbose:"subcontract_cost" }}</th>
            <td>{{ intervention.subcontract_cost|floatformat:2 }} &euro;</td>
        </tr>
        <tr>
            <th>{% trans "Mandays cost" %}</th>
            <td>
                {% for md in intervention.manday_set.all %}
                    {% if forloop.first %}
                    <table>
                    <thead><th>{% trans "Job" %}</th><th>{% trans "Mandays" %}</th><th>{% trans "Cost" %}</th></thead>
                    <tbody>
                    {% endif %}
                    <tr><td>{{ md.job }}</td><td>{{ md.nb_days|floatformat:1 }}</td><td>{{ md.cost|floatformat:2 }}</td></tr>
                    {% if forloop.last %}
                    <tr class="total"><td>{% trans "Total" %}</td><td>{{ intervention.total_manday|floatformat:1 }}</td><td>{{ intervention.total_cost_mandays|floatformat:2 }} &euro;</td></tr>
                    </tbody>
                    </table>
                    {% endif %}
                {% empty %}
                    <span class="none">{% trans "None" %}</span>
                {% endfor %}
            </td>
        </tr>
        <tr>
            <th>{{ intervention|verbose:"total_cost" }}</th>
            <td>{{ intervention.total_cost|floatformat:2 }} &euro;</td>
        </tr>
        <tr>
            <th>{% trans "Related Project" %}</th>
            <td>{% if intervention.project %}
                    {{ intervention.project.name_display|safe }}
                    ({{ intervention.project.begin_year }} - {{ intervention.project.end_year }})
                {% else %} <span class="none">{% trans "None" %}</span>
                {% endif %}
            </td>
        </tr>

        {% if intervention.is_infrastructure %}
        <tr>
            <th>{% trans "Related infrastructure" %}</th>
            <td><img src="{% static "images/infrastructure-16.png" %}"/> {{ intervention.infrastructure.name_display|safe }}</td>
        </tr>
        {% endif %}

        {% if intervention.is_signage %}
        <tr>
            <th>{% trans "Related signage" %}</th>
            <td><img src="{% static "images/signage-16.png" %}"/> {{ intervention.infrastructure.name_display|safe }}</td>
        </tr>
        {% endif %}
        <tr>
            <th>{% trans "Dimensions" %}</th>
            <td>{% trans "H:" %} {{ intervention.height|stringformat:".2f" }}m ,
                {% trans "L:" %} {{ intervention.length|stringformat:".2f" }}m ,
                {% trans "W:" %} {{ intervention.width|stringformat:".2f" }}m :
                {{ intervention.area|stringformat:".1f" }}m&sup2;
            </td>
        </tr>
        {% include "altimetry/elevationinfo_fragment.html" %}
        <tr>
            <th>{{ intervention|verbose:"description" }}</th>
            <td>{% if intervention.description %}{{ intervention.description|safe }}
                {% else %}<span class="none">{% trans "None" %}</span>{% endif %}
            </td>
        </tr>
        {% include "mapentity/trackinfo_fragment.html" %}
    </table>
    {{ block.super }}
{% endblock detailspanel %}

geotrek/maintenance/templates/maintenance/intervention_form.html
{% extends "mapentity/mapentity_form.html" %}
{% load i18n crispy_forms_tags %}

{% block mainform %}
    <form id="mainform" action="{% if object.pk %}{{ object.get_update_url }}{% else %}{{ object.get_add_url }}{% endif %}" class="form-horizontal" method="POST">
    
    {% crispy form %}
    
    <fieldset class="formset">
        {{ manday_formset.management_form }}
        {% for manday_form in manday_formset %}
            <div class="form-row inline controls controls-row {{ manday_formset.prefix }}">
            {% crispy manday_form %}
            </div>
        {% endfor %}
    </fieldset>
    
    </form>
{% endblock mainform %}


{% block extrabody %}
    {{ block.super }}
    <script type="text/javascript">
        $(window).ready(function () {
            $('#id_date').datepicker({
                autoclose: true,
                language: '{{ request.LANGUAGE_CODE }}',
                format: window.SETTINGS.date_format
            });

            // TODO: do this with crispyforms !
            $("fieldset.formset").detach().appendTo('#mainform fieldset');
            
            $(".clearfix").removeClass("clearfix");
            
            $('.form-row.inline.{{ manday_formset.prefix }}').formset({
                prefix: '{{ manday_formset.prefix }}',
                keepFieldValues: "[name='csrfmiddlewaretoken']",
                addCssClass: 'btn btn-success add-row',
                deleteCssClass: 'delete-row',
                addText: '{% trans "Add" %}',
                deleteText: '{% trans "Remove" %}', 
            });
        });
    </script>
{% endblock extrabody %}

geotrek/maintenance/templates/maintenance/maintenance_detail_fragment.html
{% load i18n geotrek_tags mapentity_tags %}

{% if modelname != "intervention" %}

<h3>{% trans "Works" %}</h3>
<table class="table">
    <tr>
        <td colspan="3">
        <strong>{% trans "Interventions" %}</strong>
            {% with columns="infrastructure,name,status,stake,total_cost,date" %}
                {% if modelname == "infrastructure" or modelname == "signage" %}
                    {% valuetable object.interventions_set.existing|dictsort:"on_infrastructure" columns=columns %}
                {% elif modelname == "project" %}
                    {% valuetable object.interventions.existing|dictsort:"on_infrastructure" enumeration=True columns=columns %}
                {% else %}
                    {% valuetable object.interventions.all|dictsort:"on_infrastructure" columns=columns %}
                {% endif %}
            {% endwith %}

            <p class="spacer"></p>

            {% is_topology_model model as is_topology_model %}
            {% if perms.maintenance.add_intervention %}
            <p class="autohide"><a href="{% url 'maintenance:intervention_add' %}{% if modelname == "infrastructure" or modelname == "signage" %}?infrastructure={{ object.pk}}{% elif is_topology_model %}?topology={{ object.pk}}{% endif %}" class="btn btn-mini btn-success">
                <i class="icon-plus icon-white"></i> {% trans "Add a new intervention" %}</a>
            </p>
            {% endif %}

        </td>
    </tr>

    {% if modelname != "project" %}
    <tr>
        <th colspan="3">{% trans "Projects" %}<br/></th>
    </tr>
        {% with object.projects.all as projects %}
            {% if projects.exists %}
            <tr>
                <th>{% trans "Name" %}</th>
                <th>{% trans "Begin year" %}</th>
                <th>{% trans "End year" %}</th>
            </tr>
        {% for project in projects %}
        <tr>
            <td>
                <a href="{% url 'maintenance:project_detail' project.pk %}">{{ project.name }}
            </td>
        <td>
                {{ project.begin_year }}
            </td>
        <td>
                {{ project.end_year }}
            </td>
        </tr>

        {% endfor %}
            {% endif %}
        {% endwith %}
    {% endif %}

</table>

{% endif %}

geotrek/maintenance/templates/maintenance/project_detail.html
{% extends "mapentity/mapentity_detail.html" %}
{% load i18n mapentity_tags %}

{% block detailspanel %}
    <table class="table-striped table-bordered table">
        <tr>
            <th>{{ project|verbose:"name" }}</th>
            <td>{{ project.name }}</td>
        </tr>
        <tr>
            <th>{{ project|verbose:"begin_year" }}</th>
            <td>{{ project.begin_year }}</td>
        </tr>
        <tr>
            <th>{{ project|verbose:"end_year" }}</th>
            <td>{{ project.end_year }}</td>
        </tr>
        <tr>
            <th>{{ project|verbose:"global_cost" }}</th>
            <td>{{ project.global_cost }} &euro;</td>
        </tr>
        <tr>
            <th>{{ project|verbose:"interventions_total_cost" }}</th>
            <td>{{ project.interventions_total_cost }} &euro;</td>
        </tr>
        <tr>
            <th>{{ project|verbose:"type" }}</th>
            <td>{% if project.type %}{{ project.type }}
                {% else %}<span class="none">{% trans "None" %}</span>{% endif %}
            </td>
        </tr>
        <tr>
            <th>{{ project|verbose:"domain" }}</th>
            <td>{% if project.domain %}{{ project.domain }}
                {% else %}<span class="none">{% trans "None" %}</span>{% endif %}
            </td>
        </tr>
        <tr>
            <th>{{ project|verbose:"constraint" }}</th>
            <td>{% if project.constraint %}{{ project.constraint|safe }}
                {% else %}<span class="none">{% trans "None" %}</span>{% endif %}
            </td>
        </tr>
        <tr>
            <th>{{ project|verbose:"project_owner" }}</th>
            <td>{% if project.project_owner %}{{ project.project_owner }}
                {% else %}<span class="none">{% trans "None" %}</span>{% endif %}
            </td>
        </tr>
        <tr>
            <th>{{ project|verbose:"project_manager" }}</th>
            <td>{% if project.project_manager %}{{ project.project_manager }}
                {% else %}<span class="none">{% trans "None" %}</span>{% endif %}
            </td>
        </tr>
        <tr>
            <th>{{ project|verbose:"contractors" }}</th>
            <td>
                {% valuelist project.contractors.all %}
            </td>
        </tr>
        <tr>
            <th>{% trans "Fundings" %}</th>
            <td>
                {% for f in project.funding_set.all %}
                    {% if forloop.first %}<ul>{% endif %}
                    <li>
                    {% blocktrans with f.amount as amount and f.organism as organism %}
                    {{ amount }}€ by {{ organism }}
                    {% endblocktrans %}
                    </li>
                    {% if forloop.last %}</ul>{% endif %}
                {% empty %}
                    <span class="none">{% trans "None" %}</span>
                {% endfor %}
            </td>
        </tr>
        <tr>
            <th>{{ project|verbose:"comments" }}</th>
            <td>{% if project.comments %}{{ project.comments|safe }}
                {% else %}<span class="none">{% trans "None" %}</span>{% endif %}
            </td>
        </tr>
        {% include "mapentity/trackinfo_fragment.html" %}
    </table>
    {{ block.super }}
{% endblock detailspanel %}


{% block extrabody %}
    {{ block.super }}
    <script type="text/javascript">
        $(window).on('detailmap:ready', function (e, data) {
            var map = data.map;

            // Remove project geometry layer (GeometryCollection)
            map.removeLayer(data.layer);

            //
            // Load intervention layer filtered on project
            var layer_url = "{% url 'maintenance:intervention_layer' %}?project={{ object.pk}}";
            var DETAIL_STYLE = L.Util.extend(window.SETTINGS.map.styles.detail, {clickable: true});

            var layer = new L.ObjectsLayer(layer_url, {
                style: DETAIL_STYLE,
                objectUrl: interventionUrl,
                onEachFeature: showInterventionLabel,
                modelname: 'intervention',
            });
            layer.addTo(map);
            layer.on('data:load', function (e) {
                layer.showEnumeration();
            });


            function showInterventionLabel (geojson, layer) {
                if (geojson.properties.name) layer.bindLabel(geojson.properties.name);
            }

            function interventionUrl(properties, layer) {
                return window.SETTINGS.urls.detail.replace(new RegExp('modelname', 'g'), 'intervention')
                                      .replace('0', properties.pk);
            };
        });
    </script>
{% endblock extrabody %}

geotrek/maintenance/templates/maintenance/project_form.html
{% extends "mapentity/mapentity_form.html" %}
{% load i18n crispy_forms_tags %}

{% block mainform %}
    <form id="mainform" action="{% if object.pk %}{{ object.get_update_url }}{% else %}{{ object.get_add_url }}{% endif %}" class="form-horizontal" method="POST">
    
    {% crispy form %}
    
    <fieldset class="formset">
        {{ funding_formset.management_form }}
        {% for funding_form in funding_formset %}
            <div class="form-row inline controls controls-row {{ funding_formset.prefix }}">
            {% crispy funding_form %}
            </div>
        {% endfor %}
    </fieldset>
    
    </form>
{% endblock mainform %}

{% block extrabody %}
{{ block.super }}
<script type="text/javascript">
$(function() {
    // TODO: do this with crispyforms !
    $("fieldset.formset").detach().appendTo('#mainform fieldset');
    
    $(".clearfix").removeClass("clearfix");
    
    $('.form-row.inline.{{ funding_formset.prefix }}').formset({
        prefix: '{{ funding_formset.prefix }}',
        keepFieldValues: "[name='csrfmiddlewaretoken']",
        addCssClass: 'btn btn-success add-row',
        deleteCssClass: 'delete-row',
        addText: '{% trans "Add funding" %}',
        deleteText: '{% trans "Remove" %}', 
    })
})
</script>
{% endblock extrabody %}